// Shared roles data that can be imported by both role management and admin pages
export const rolesData = [
  {
    id: 1,
    name: "Admin",
    createdDate: "10/05/2025",
    createdBy: "System",
    updatedDate: "10/05/2025",
    updatedBy: "System",
    description: "Full system access with all permissions",
    permissions: {
      admin: {
        users: { create: true, read: true, update: true, delete: true },
        roles: { create: true, read: true, update: true, delete: true },
        "reference-data": { create: true, read: true, update: true, delete: true },
        settings: { create: true, read: true, update: true, delete: true },
      },
      "product-management": {
        products: { create: true, read: true, update: true, delete: true },
        manufacturing: { create: true, read: true, update: true, delete: true },
        specifications: { create: true, read: true, update: true, delete: true },
        deadlines: { create: true, read: true, update: true, delete: true },
        analytics: { create: true, read: true, update: true, delete: true },
      },
      "task-management": {
        alerts: { create: true, read: true, update: true, delete: true },
        repository: { create: true, read: true, update: true, delete: true },
        assignments: { create: true, read: true, update: true, delete: true },
        dashboards: { create: true, read: true, update: true, delete: true },
        "performance-analytics": { create: true, read: true, update: true, delete: true },
      },
      "inventory-management": {
        skus: { create: true, read: true, update: true, delete: true },
        wastage: { create: true, read: true, update: true, delete: true },
        procurement: { create: true, read: true, update: true, delete: true },
        analytics: { create: true, read: true, update: true, delete: true },
      },
      "asset-management": {
        assets: { create: true, read: true, update: true, delete: true },
        dashboard: { create: true, read: true, update: true, delete: true },
      },
      "audit-management": {
        forms: { create: true, read: true, update: true, delete: true },
        reports: { create: true, read: true, update: true, delete: true },
      },
    },
  },
  {
    id: 2,
    name: "Task Manager",
    createdDate: "10/05/2025",
    createdBy: "Admin",
    updatedDate: "10/05/2025",
    updatedBy: "Admin",
    description: "Manages tasks and workflows",
    permissions: {
      "task-management": {
        alerts: { create: true, read: true, update: true, delete: true },
        repository: { create: true, read: true, update: true, delete: true },
        assignments: { create: true, read: true, update: true, delete: true },
        dashboards: { create: true, read: true, update: true, delete: true },
        "performance-analytics": { create: true, read: true, update: true, delete: false },
      },
      "inventory-management": {
        skus: { create: false, read: true, update: false, delete: false },
        wastage: { create: false, read: true, update: false, delete: false },
        procurement: { create: false, read: true, update: false, delete: false },
        analytics: { create: false, read: true, update: false, delete: false },
      },
    },
  },
  {
    id: 3,
    name: "Operation Manager",
    createdDate: "10/05/2025",
    createdBy: "Admin",
    updatedDate: "10/05/2025",
    updatedBy: "Admin",
    description: "Manages operations and workflows",
    permissions: {
      "task-management": {
        alerts: { create: true, read: true, update: true, delete: false },
        repository: { create: true, read: true, update: true, delete: false },
        assignments: { create: true, read: true, update: true, delete: false },
        dashboards: { create: false, read: true, update: false, delete: false },
        "performance-analytics": { create: false, read: true, update: false, delete: false },
      },
      "inventory-management": {
        skus: { create: true, read: true, update: true, delete: false },
        wastage: { create: true, read: true, update: true, delete: false },
        procurement: { create: true, read: true, update: true, delete: false },
        analytics: { create: false, read: true, update: false, delete: false },
      },
      "asset-management": {
        assets: { create: true, read: true, update: true, delete: false },
        dashboard: { create: false, read: true, update: false, delete: false },
      },
    },
  },
  {
    id: 4,
    name: "Product Manager",
    createdDate: "10/05/2025",
    createdBy: "Admin",
    updatedDate: "10/05/2025",
    updatedBy: "Admin",
    description: "Manages product catalog and manufacturing processes",
    permissions: {
      "product-management": {
        products: { create: true, read: true, update: true, delete: true },
        manufacturing: { create: true, read: true, update: true, delete: true },
        specifications: { create: true, read: true, update: true, delete: true },
        deadlines: { create: true, read: true, update: true, delete: false },
        analytics: { create: false, read: true, update: false, delete: false },
      },
      "inventory-management": {
        skus: { create: false, read: true, update: false, delete: false },
        wastage: { create: false, read: true, update: false, delete: false },
        procurement: { create: false, read: true, update: false, delete: false },
        analytics: { create: false, read: true, update: false, delete: false },
      },
    },
  },
  {
    id: 5,
    name: "Executive",
    createdDate: "10/05/2025",
    createdBy: "Admin",
    updatedDate: "10/05/2025",
    updatedBy: "Admin",
    description: "Executive level access",
    permissions: {
      admin: {
        users: { create: false, read: true, update: false, delete: false },
        roles: { create: false, read: true, update: false, delete: false },
        "reference-data": { create: false, read: true, update: false, delete: false },
        settings: { create: false, read: true, update: false, delete: false },
      },
      "product-management": {
        products: { create: false, read: true, update: false, delete: false },
        manufacturing: { create: false, read: true, update: false, delete: false },
        specifications: { create: false, read: true, update: false, delete: false },
        deadlines: { create: false, read: true, update: false, delete: false },
        analytics: { create: false, read: true, update: false, delete: false },
      },
      "task-management": {
        alerts: { create: false, read: true, update: false, delete: false },
        repository: { create: false, read: true, update: false, delete: false },
        assignments: { create: false, read: true, update: false, delete: false },
        dashboards: { create: false, read: true, update: false, delete: false },
        "performance-analytics": { create: false, read: true, update: false, delete: false },
      },
      "inventory-management": {
        skus: { create: false, read: true, update: false, delete: false },
        wastage: { create: false, read: true, update: false, delete: false },
        procurement: { create: false, read: true, update: false, delete: false },
        analytics: { create: false, read: true, update: false, delete: false },
      },
      "asset-management": {
        assets: { create: false, read: true, update: false, delete: false },
        dashboard: { create: false, read: true, update: false, delete: false },
      },
      "audit-management": {
        forms: { create: false, read: true, update: false, delete: false },
        reports: { create: false, read: true, update: false, delete: false },
      },
    },
  },
  {
    id: 6,
    name: "Technician",
    createdDate: "10/05/2025",
    createdBy: "Task Manager",
    updatedDate: "10/05/2025",
    updatedBy: "Task Manager",
    description: "Technical staff with specific skills",
    permissions: {
      "task-management": {
        alerts: { create: false, read: true, update: true, delete: false },
        repository: { create: false, read: true, update: false, delete: false },
        assignments: { create: false, read: true, update: true, delete: false },
        dashboards: { create: false, read: true, update: false, delete: false },
        "performance-analytics": { create: false, read: true, update: false, delete: false },
      },
      "asset-management": {
        assets: { create: false, read: true, update: true, delete: false },
        dashboard: { create: false, read: true, update: false, delete: false },
      },
    },
  },
  {
    id: 7,
    name: "Worker",
    createdDate: "10/05/2025",
    createdBy: "Task Manager",
    updatedDate: "10/05/2025",
    updatedBy: "Task Manager",
    description: "Performs assigned tasks",
    permissions: {
      "task-management": {
        alerts: { create: false, read: true, update: false, delete: false },
        repository: { create: false, read: true, update: false, delete: false },
        assignments: { create: false, read: true, update: true, delete: false },
        dashboards: { create: false, read: true, update: false, delete: false },
        "performance-analytics": { create: false, read: false, update: false, delete: false },
      },
    },
  },
]
